name: Trigger Deploy Webhook
run-name: ${{ github.actor }} deploys service
on:
  push:
    branches:
      - main
    paths:
      - 'service/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        if: ${{ vars.DEPLOY_WEBHOOK != '' }}
        run: curl -X POST ${{ vars.DEPLOY_WEBHOOK }}
